### ISSUE TITLE
可不可以在插入多行时,  考虑缩进

### ISSUE THREAD

**Issue by lovedanzhi** [bennyhuo/Kotlin-Trim-Indent#1]
比如这段代码
```kotlin
val s1 = """
    if(a > 1) {
        return true
    }
""".trimIndent()
val s2 = """
    def test(a) {
        $s1
    }
""".trimIndent()
println(s2)
```
会打印
```
def test(a) {
    if(a > 1) {
    return true
}
}
```
能不能打印成这样?
```
def test(a) {
    if(a > 1) {
        return true
    }
}
```

**Comment by bennyhuo** [comment]
这需要在运行时对 s1 的每一行都增加一个缩进。理论上也可以做，但不太适合放到这里。

不过，你说的这个，确实是个很好的点，我也遇到过这种实际的应用场景。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月31日(周一) 上午9:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bennyhuo/Kotlin-Trim-Indent] 可不可以在插入多行时,  考虑缩进 (Issue #1)

**Comment by bennyhuo** [comment]
已经实现了，试一下 1.7.10.3-SNAPSHOT

**Comment by bennyhuo** [comment]
已经发了 1.7.10.3.
